# ----------------------------------------------------------------------------------------------------------------
# PyComInt: Communication interface for chemical plants
# https://github.com/SimMarkt/PyComInt

# config_sql.yaml: 
# > Configuration for the SQL database (PostgreSQL)
# ----------------------------------------------------------------------------------------------------------------


# PostgreSQL connection parameters
DB_HOST : localhost   # IP Address: 127.0.0.1
DB_PORT : 5432
DB_NAME : Orbit
DB_USER : python_opcua_user'       # 'postgres'
DB_PASSWORD : ...
DB_TABLE : orbit_data
DB_COLUMS : ['timestamp', 'real_ph']