# ----------------------------------------------------------------------------------------------------------------
# PyComInt: Communication interface of chemical plants
# https://github.com/SimMarkt/PyComInt

# config_opcua.yaml: 
# > Configuration for the OPCUA server with the tagged nodes
# > Application:    Power-to-Gas process with an proton exchange membrane electrolyzer (PEMEL) as Modbus client and a biological methanation unit (BM)
#                   with a programmable logic controller providing an OPCUA server
# 
# ----------------------------------------------------------------------------------------------------------------

# OPCUA server URL and credentials
URL : ...
USERNAME : OPCUA_user_1
PASSWORD : ...

# NodeID for the variables
OPCUA_NODE_IDs : ["ns=7;s=::AsGlobalPV:real_Ph",
                  "ns=7;s=::AsGlobalPV:real_Ph"]
H2_FLOW_ID : ns=7;s=::AsGlobalPV:real_h2_flowrate     # Node ID of the H2 flow rate set point (for PEMEL control)
