# ----------------------------------------------------------------------------------------------------------------
# PyComInt: Communication interface for chemical plants
# https://github.com/SimMarkt/PyComInt

# config_sql.yaml: 
# > Configuration for the SQL database (PostgreSQL)
# ----------------------------------------------------------------------------------------------------------------


# PostgreSQL connection parameters
DB_HOST : ...                       # If the SQL database is present on the same server (Virtual Environment: "127.0.0.1"/"localhost"; Docker Container: "host.docker.internal")
DB_PORT : 5432                      # Database port
DB_NAME : ...                       # Database name
DB_USER : python_opcua_user'          # Username
DB_PASSWORD : ...                     # Password
DB_TABLE : ...                 # Table with data
DB_COLUMNS : ['timestamp', 'real_temperature', 'real_pressure', 'real_methane_production',
              'error', 'modeoff', 'modemanual', 'modeautomatic', 'safety', 'main_fan', 
              'fan', 'outer_cooling_fan', 'outer_cooling_pump', 'h2_cooling', 
              'h2_cooling_temperature_reached', 'valve', 'pump1', 'pump2', 'pump3', 'empty',
              'el_power_act', 'el_current_act', 'el_h2_pressure_act', 'el_conductance_act', 
              'el_temp_In_act', 'el_propventil', 'el_calch2flow_act', 'el_calch2volume_sum', 'el_1_temp_out_act', 
              'el_2_temp_out_act', 'el_3_temp_out_act', 'el_4_temp_out_act', 'el_5_temp_out_act', 'el_h2_cooling_temp_act']