# ----------------------------------------------------------------------------------------------------------------
# PyComInt: Communication interface for chemical plants
# https://github.com/SimMarkt/PyComInt

# config_sql.yaml: 
# > Configuration for the SQL database (PostgreSQL)
# ----------------------------------------------------------------------------------------------------------------


# PostgreSQL connection parameters
DB_HOST : localhost                   # IP Address: 127.0.0.1
DB_PORT : 5432                        # Database port
DB_NAME : ...                       # Database name
DB_USER : python_opcua_user'          # Username
DB_PASSWORD : ...                     # Password
DB_TABLE : ...                 # Table with data
DB_COLUMNS : ['timestamp', 'real_var1', 'real_var2'] # Column descriptions